# Generated by Django 6.0.6 on 2026-08-22 22:47

import django.core.validators
import ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_orden_ordenitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenitem',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='ordenitem',
            name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), ecommerce.models.validate_producto_image_size]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0, help_text='Precio en CLP (sin puntos ni comas)'),
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='OrdenItem',
        ),
    ]
