# Generated by Django 6.0.2 on 2026-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="Alexis Lara Viveros", max_length=100),
                ),
                (
                    "cv_pdf",
                    models.FileField(
                        help_text="Sube tu CV en formato PDF", upload_to="cv/"
                    ),
                ),
                ("link_linkedin", models.URLField(help_text="Tu enlace de LinkedIn")),
                (
                    "link_github",
                    models.URLField(help_text="Tu enlace de GitHub principal"),
                ),
                (
                    "correo",
                    models.EmailField(
                        help_text="Tu correo de contacto profesional", max_length=254
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion_corta", models.TextField()),
                (
                    "contexto_social",
                    models.TextField(
                        help_text="¿Qué problema humano o social resuelve?"
                    ),
                ),
                (
                    "metodologia_ux",
                    models.TextField(
                        blank=True,
                        help_text="¿Usaste entrevistas, observación, encuestas?",
                    ),
                ),
                (
                    "tecnologias",
                    models.CharField(
                        help_text="Ej: Python, Django, SQLite", max_length=200
                    ),
                ),
                ("imagen", models.ImageField(upload_to="proyectos/")),
                ("link_github", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("TECH", "Technical (Python/Django)"),
                            ("UX", "UX Research & Anthropology"),
                            ("SOFT", "Soft Skills"),
                        ],
                        max_length=4,
                    ),
                ),
                ("nivel", models.IntegerField(help_text="Del 1 al 100")),
            ],
        ),
    ]
