# Generated by Django 6.0.2 on 2026-03-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "ocupacion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Reclutador, Colega, Cliente",
                        max_length=100,
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "aprobado",
                    models.BooleanField(
                        default=False, help_text="Marcar para mostrar en la web"
                    ),
                ),
            ],
        ),
    ]
