# Generated by Django 6.0.2 on 2026-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_testimonio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="intereses/")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        help_text="¿Por qué te interesa esta imagen?",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Testimonio",
        ),
        migrations.AddField(
            model_name="perfil",
            name="contar_sobre_mi",
            field=models.TextField(
                blank=True,
                help_text="Cuenta aquí tu historia de forma cercana",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="correo",
            field=models.EmailField(
                blank=True,
                help_text="Tu correo de contacto profesional",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="cv_pdf",
            field=models.FileField(
                blank=True,
                help_text="Sube tu CV en formato PDF",
                null=True,
                upload_to="cv/",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="link_github",
            field=models.URLField(
                blank=True, help_text="Tu enlace de GitHub principal"
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="link_linkedin",
            field=models.URLField(blank=True, help_text="Tu enlace de LinkedIn"),
        ),
    ]
