# Generated by Django 6.0.6 on 2026-08-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_interes_delete_testimonio_perfil_contar_sobre_mi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('investigacion', 'Investigación + código'), ('producto', 'Producto real'), ('demo', 'Demo técnica')], default='investigacion', max_length=20),
        ),
    ]
