# Generated by Django 6.0.6 on 2026-08-22 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_proyecto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='nivel',
            field=models.IntegerField(help_text='Del 1 al 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
