# Generated by Django 6.0.6 on 2026-10-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_skill_nivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-destacado', 'id']},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='advertencia',
            field=models.TextField(blank=True, help_text="Aviso visible en la tarjeta, ej: 'Demo técnica, no es un producto en producción'", verbose_name='Advertencia'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='anio',
            field=models.CharField(blank=True, help_text='Año o período, ej: 2026', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='capturas',
            field=models.JSONField(blank=True, default=list, help_text='Rutas de static + pie de foto, ej: [{"src": "main/estacion/portada-desktop.webp", "alt": "Portada", "pie": "Portada del sitio", "portada": true}]', verbose_name='Capturas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cliente',
            field=models.CharField(blank=True, help_text='Cliente o negocio', max_length=120),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Lo convierte en el caso de estudio destacado sobre el hero'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='etapas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de pasos, ej: [{"etiqueta": "Observación", "titulo": "Cero presencia digital", "texto": "..."}]', verbose_name='Etapas del proceso'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='link_interno',
            field=models.CharField(blank=True, help_text='Ruta dentro de este sitio, ej: /apoyo-mutuo/ (se abre en la misma pestaña)', max_length=200),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='metodo',
            field=models.TextField(blank=True, help_text='Cómo investigué o cómo decidí construirlo', verbose_name='Método'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='metricas',
            field=models.JSONField(blank=True, default=list, help_text='Cifras reales con su fuente, ej: [{"valor": "10.111", "etiqueta": "personas vieron el perfil", "nota": "Google · últimos 28 días"}]', verbose_name='Métricas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='problema',
            field=models.TextField(blank=True, help_text='Qué encontré en terreno', verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='resultado',
            field=models.TextField(blank=True, help_text='Qué cambió. Solo hechos verificables', verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='rol',
            field=models.CharField(blank=True, help_text='Qué hiciste tú, en una línea', max_length=160),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='terminos',
            field=models.JSONField(blank=True, default=list, help_text='Qué búsquedas muestran el proyecto, ej: [{"termino": "restaurants", "busquedas": 3679}]', verbose_name='Términos de búsqueda'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='traduccion',
            field=models.TextField(blank=True, help_text='Qué construiste', verbose_name='Traducción'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='url_produccion',
            field=models.URLField(blank=True, help_text='Sitio en producción (no es repositorio)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='visible',
            field=models.BooleanField(default=True, help_text='Desmarca para ocultarlo del portafolio sin borrarlo'),
        ),
    ]
