# Generated by Django 6.0.6 on 2026-08-22 22:47

import comunidad.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_habilidad_imagen_alter_perfil_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habilidades/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), comunidad.models.validate_image_size]),
        ),
        migrations.AddConstraint(
            model_name='intercambio',
            constraint=models.UniqueConstraint(fields=('solicitante', 'habilidad'), name='uniq_solicitante_habilidad'),
        ),
    ]
